version: "3.8"
services:
  # ---------------  PostgreSQL ---------------
  db:
    image: postgres:alpine3.15
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password12*
      POSTGRES_DB: hrms
    volumes:
      - postgre_volume:/var/lib/postgresql/data

  # ---------------  PGADMIN ---------------
  pgAdmin:
    image: dpage/pgadmin4:6.9
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@enginyenice.com
      PGADMIN_DEFAULT_PASSWORD: Password12*

volumes:
  postgre_volume: